#!/bin/sh

. "$XDG_FUNCTIONS_HOME"/ssh.sh
. "$XDG_FUNCTIONS_HOME"/dotfiles.sh

dotfiles_repo=git@git.seago.io:seagoj/dotfiles.git

set_origin() {
    git remote rm origin && \
    git remote add origin "$dotfiles_repo" && \
    git submodule update --recursive --init
}

osinstall ssh ssh-copy-id && \
ssh_reset_permissions && \
dotfiles_reset_origin "$dotfiles_repo" && \
ssh ${@}
