#!/usr/bin/env bash

osinstall ssh ssh-copy-id
SSH_CONFIG=${HOME}/.ssh
declare -a KEYS=($(find ${SSH_CONFIG}/ -name "*.pub"))
for i in "${KEYS[@]%.pub}"; do
    chmod 600 ${i}
    chmod 600 ${i}.pub
done
chmod 644 ${SSH_CONFIG}/known_hosts
chmod 755 "${SSH_CONFIG}"

git remote rm origin &&\
    git remote add origin git@github.com:seagoj/dotfiles.git &&\
    git submodule update --recursive --init
