#!/usr/bin/env bash

echo "installing..."

. "${XDG_FUNCTIONS_DIR:-$HOME/.local/functions}"/ssh.sh
. "${XDG_FUNCTIONS_DIR:-$HOME/.local/functions}"/sourced/osinstall.sh

osinstall ssh

if ! which ssh-copy-id >/dev/null; then
	osinstall ssh-copy-id
fi

ssh::reset_permissions

git remote rm origin &&\
	git remote add origin git@github.com:seagoj/dotfiles.git &&\
	git submodule update --recursive --init
