#!/usr/bin/env bash

. "${XDG_FUNCTIONS_DIR:-$HOME/.local/functions}"/dotfiles.sh

installMac() {
    dotfiles::bootstrap python

    general::sudo 'pip install turses'
}

installArch() {
    dotfiles::bootstrap python

    general::sudo 'pip install turses'
}

dotfiles::install turses
