#!/usr/bin/env bash

package=dmenu
localRepo="${CODE:-HOME/code}"/suckless/"${package}"
remoteRepo=git://git.suckless.org/"${package}"
patches=(
    http://tools.suckless.org/dmenu/patches/fuzzymatch/dmenu-fuzzymatch-4.9.diff
)

. "$XDG_FUNCTIONS_DIR"/git.sh
. "$XDG_FUNCTIONS_DIR"/suckless.sh

git::clone "${remoteRepo}" "${localRepo}" 2>/dev/null
cd "$localRepo" && \
    suckless::applyPatches "${patches[@]}" && \
    suckless::install

wget "https://tools.suckless.org/dmenu/scripts/run-recent" -O "${HOME}"/.local/bin/run-recent && \
    chmod 0700 "${HOME}"/.local/bin/run-recent

run-recent ${@}
