#!/bin/sh

patches=" \
    http://tools.suckless.org/dmenu/patches/fuzzymatch/dmenu-fuzzymatch-4.9.diff \
"

. "$XDG_FUNCTIONS_HOME"/suckless.sh

project=$(basename "${0}")
suckless_build "$project" && \
"$project" ${@}

wget "https://tools.suckless.org/dmenu/scripts/run-recent" -O "${HOME}"/.local/bin/run-recent && \
    chmod 0700 "${HOME}"/.local/bin/run-recent

run-recent ${@}
