#!/usr/bin/env bash

case $OS_TYPE in
Darwin | Mac)
    brew tap homebrew/dupes
    brew tap homebrew/versions
    brew tap homebrew/homebrew-php
    brew unlink php56
    brew install php70
    ;;
Arch)
    asdf plugin-add php
    asdf install php 7.3.9
    asdf global php 7.3.9
    ;;
*)
    osinstall php
    ;;
esac
