#!/bin/sh

. "${XDG_FUNCTIONS_HOME}"/sourced.sh
source_file "${XDG_FUNCTIONS_HOME}"/asdf.sh

# install dap
cd "${XDG_SOURCE_HOME}"/vscode-php-debug && \
	npm install && \
	npm run build

brew install libsodium re2c bison zlib && \
	plugin=php asdf_wrapper ${@}
