#!/usr/bin/env bash

brew install neovim readline xz openssl

if ! which pyenv &>/dev/null; then
    curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
fi

eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

PYTHON2_VERSION='2.7.15'
PYTHON3_VERSION='3.7.0'

yes | CFLAGS="-I$(brew --prefix openssl)/include" \
    LDFLAGS="-L$(brew --prefix openssl)/lib" \
    pyenv install "${PYTHON2_VERSION}"

yes | CFLAGS="-I$(brew --prefix openssl)/include" \
    LDFLAGS="-L$(brew --prefix openssl)/lib" \
    pyenv install "${PYTHON3_VERSION}"

pyenv virtualenv "${PYTHON2_VERSION}" neovim2
pyenv virtualenv "${PYTHON3_VERSION}" neovim3

CFLAGS="-I$(brew --prefix openssl)/include" \
    LDFLAGS="-L$(brew --prefix openssl)/lib" \
    pyenv doctor

pyenv activate neovim2
pip install neovim
pyenv which python

pyenv activate neovim3
pip install neovim
pyenv which python

# The following is optional, and the neovim3 env is still active
# This allows flake8 to be available to linter plugins regardless
# of what env is currently active.  Repeat this pattern for other
# packages that provide cli programs that are used in Neovim.
pip install flake8
ln -s `pyenv which flake8` ~/.local/bin/flake8  # Assumes that $HOME/bin is in $PATH
