#!/usr/bin/env bash

. $HOME/.local/functions/dotfiles.sh

FORK=https://github.com/seagoj/vimclip
REPO=https://github.com/hrantzsch/vimclip

dotfiles::update_repo "${FORK:-$REPO}" vimclip
if [[ -L "$HOME/.local/bin/vimclip" ]]; then
    rm "$HOME/.local/bin/vimclip"
fi
ln -s "$PWD"/vimclip $HOME/.local/bin/vimclip

vimclip $@
