#!/usr/bin/env bash

package=surf
localRepo="${CODE:-HOME/code}"/suckless/${package}
remoteRepo="git://git.suckless.org/${package}"
version="${SURF_VERSION:-2.0}"

patches=(
    "homepage"
)

. "$XDG_FUNCTIONS_DIR"/git.sh
. "$XDG_FUNCTIONS_DIR"/suckless.sh

git::clone "${remoteRepo}" "${localRepo}" 2>/dev/null
cd "$localRepo" && \
    suckless::applyPatches "${patches[@]}" && \
    suckless::install

"${package}" ${@}
