#!/bin/sh

osinstall gstreamer webkit2gtk

patches=" \
    http://surf.suckless.org/patches/homepage/surf-2.0-homepage.diff \
"

. "$XDG_FUNCTIONS_HOME"/suckless.sh

suckless_build $(basename "${0}") && \
$(basename "${0}") ${@}
