#!/usr/bin/env bash

# includes
includes=($(ls "$XDG_CONFIG_HOME"/bspwm/*.sh))
for include in "${includes[@]}"; do
    source "$include"
done

# config
bspc config normal_border_color  "$unfocused"
bspc config active_border_color  "$unfocused"
bspc config focused_border_color "$focused"
bspc config preset_border_color  "$select"
bspc config border_width         2
bspc config window_gap           24
bspc config split_ratio          0.50
bspc config focus_follows_pointer true
## monocle
bspc config borderless_monocle   true
bspc config gapless_monocle      true
### cover polybar
bspc config top_monocle_padding  -35

# run launch script
$XDG_CONFIG_HOME/bspwm/launch
