#!/usr/bin/env bash

sxhkd &

bspc monitor -d I II III IV V

# set wallpaper
feh --bg-scale $XDG_CONFIG_HOME/bspwm/wall.png

# launch bar
$XDG_CONFIG_HOME/polybar/launch.sh

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# cover polybar when monocle
bspc config top_monocle_padding  -31

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

$TERMINAL&
$BROWSER&
