#!/bin/sh

installNeovimMac() {
    brew install neovim
    pip2 install --upgrade pip neovim
    pip3 install --install pip neovim flake8
}

installNeovimDebian() {
    sudo apt-get install neovim python-neovim python3-neovim
}

fromSource() {
    osinstall cmake unzip
    cd "$HOME"/.local/src/neovim && \
	osinstall base-devel cmake unzip ninja tree-sitter xsel && \
	make CMAKE_BUILD_TYPE=Release && \
	sudo make install
    pip2 install --upgrade pip neovim
    pip3 install --upgrade pip neovim
}

case "$(uname -s)" in
Darwin | Mac)
    installNeovimMac
    brew tap neovim/neovim
    brew tap rogual/neovim-dot-app
    brew install neovim-dot-app
    ln -s /usr/local/opt/neovim-dot-app /Applications
    ;;
Linux)
    fromSource
    ;;
Debian)
    installNeovimDebian
    ;;
*)
    DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
    echo "Please define ${DIR##*/} installation for ${OS_TYPE}"
    exit 1
    ;;
esac
