#!/bin/sh

installNeovimMac() {
    brew install --HEAD luajit
    brew install --HEAD neovim
#     pip2 install --upgrade pip neovim
#     pip3 install --install pip neovim flake8
}

installNeovimDebian() {
    sudo apt-get install neovim python-neovim python3-neovim
}

fromSource() {
    osinstall cmake unzip base-devel cmake unzip ninja tree-sitter-git xsel && \
    sudo rm -rf "$HOME"/.local/src/neovim/.deps 
    cd "$HOME"/.local/src/neovim && \
	sudo make LIBUV_DIR=/usr/lib CMAKE_BUILD_TYPE=RelWithDebInfo && \
	sudo make install && \
	pip2 install --upgrade pip neovim && \
	pip3 install --upgrade pip neovim
}

case "$(uname -s)" in
Darwin | Mac)
    installNeovimMac
    ;;
Linux)
    fromSource
    ;;
Debian)
    installNeovimDebian
    ;;
*)
    DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
    echo "Please define ${DIR##*/} installation for ${OS_TYPE}"
    exit 1
    ;;
esac
