#!/usr/bin/env bash

case $OS_TYPE in
Darwin | Mac)
    updateRepoAndCd git://github.com/VitaliyRodnenko/geeknote.git geeknote &&\
        sudo python setup.py install
    popd
    ;;
*)
    updateRepoAndCd git://github.com/VitaliyRodnenko/geeknote.git geeknote &&\
        osinstall python2-setuptools &&\
        sudo python2 setup.py install
    popd
    ;;
esac
