#!/usr/bin/env bash

if [[ $OS_TYPE = "mac" ]]; then
    osinstall qt4 Caskroom/cask/virtualbox
else
    osinstall virtualbox virtualbox-host-modules-arch
    sudo modprobe vboxdrv
    # Require virtualbox 5.* for Bonfyre
    # yay -S qt4 virtualbox-5
    # osinstall qt4 virtualbox
fi
