#!/usr/bin/env bash

REMOTE=https://github.com/vifm/vifm
LOCAL=/tmp/vifm

if [ ! -d "${LOCAL}" ]; then
    git clone --recurse-submodules "${REMOTE}" "${LOCAL}" && cd "${LOCAL}"
else
    cd "${LOCAL}" && git pull origin master
fi

scripts/fix-timestamps && \
./configure && \
make && \
sudo make install

vifm ${@}
