#!/bin/sh

if [[ $OS_TYPE = "mac" ]]; then
		cargo install --git https://github.com/jwilm/alacritty
		cd ~/.cargo/git/alacritty*/ && make app && cp -r target/release/osx/Alacritty.app /Applications/
else
		osinstall alacritty
fi
