#!/bin/sh

read oldrev newrev refname
docRoot=/home/www
emailScriptPath=/opt/smrsh/processEmail.pl

branch=${refname#refs/heads/}
tag=${refname#refs/tags/}
branch_allowed=$branch

source $docRoot/.env

if [ "$tag" != "$refname" ]; then
	git --git-dir=$docRoot/.git --work-tree=$docRoot fetch --tags
	mysql -u$DB_USER -p$DB_PASS $DB_NAME < $docRoot/mysql/$tag.sql
elif [ "$branch" != "$branch_allowed" ]; then
	echo Only the $branch_allowed branch is autoupdated
else
	rm $emailScriptPath
	git --git-dir=$docRoot/.git --work-tree=$docRoot fetch --all
	git --git-dir=$docRoot/.git --work-tree=$docRoot reset --hard origin/$branch
	ln -s $docRoot/_processEmail/processEmail.pl $emailScriptPath
	cd $docRoot && composer install --no-dev --no-scripts
	echo $branch updated
fi
