#!/bin/sh

LOCAL="$HOME"/.local/src/vimb

c_install() {
    cd "$LOCAL" && \
    git checkout master && \
    make && \
    sudo make install && \
    make clean
}

vimb_install() {
    osinstall gstreamer-vaapi webkit2gtk && \
    c_install && \
    vimb "${@}"
}

vimb_install
