#!/bin/sh

LOCAL="$HOME"/.local/src/vimb

c_install() {
    cd "$LOCAL" && \
    make && \
    sudo make install && \
    make clean
}

osinstall gstreamer-vaapi webkit2gtk && \
c_install && \
vimb "${@}"
