#!/usr/bin/env bash

. "${HOME}"/.local/functions/dotfiles.sh

installNeovimMac() {
    brew install neovim
    pip2 install --upgrade pip neovim
    pip3 install --install pip neovim flake8
}

installNeovimDebian() {
    sudo apt-get install neovim python-neovim python3-neovim
}

installSourcerer() {
    if [[ ! -f ${XDG_CONFIG_HOME}/nvim/colors/sourcerer.vim ]]; then
        git clone git://github.com/xero/sourcerer.git $CODE/sourcerer
        ln -s ${CODE}/sourcerer/sourcerer.vim $XDG_CONFIG_HOME/nvim/colors/sourcerer.vim
    fi
}

installPlugins() {
    nvim -c :PackInstall
}

installESLint() {
    if ! which eslint &>/dev/null; then
        general::sudo npm install -g eslint
    fi
}

installVimv() {
    if ! which vimv &>/dev/null; then
        general::update_repo git://github.com/thameera/vimv.git vimv
        popd
        ln -s "${CODE}/vimv/vimv" "${HOME}/.local/bin/vimv"
        chmod +x "{HOME}/.local/bin/vimv"
    fi
}

case "$(uname -s)" in
Darwin | Mac)
    installNeovimMac
    installSourcerer
    installPlugins
    brew tap neovim/neovim
    brew tap rogual/neovim-dot-app
    brew install neovim-dot-app
    ln -s /usr/local/opt/neovim-dot-app /Applications
    ;;
Linux)
    osinstall neovim python2-neovim python-neovim xsel
    pip2 install --upgrade pip neovim
    pip3 install --upgrade pip neovim flake8
    # if [[ ! -f  ~/.local/bin/flake8 ]]; then
    #     ln -s `pyenv which flake8` ~/.local/bin/flake8  # Assumes that $HOME/bin is in $PATH
    # fi

    installSourcerer
    installPlugins
    ;;
Debian)
    installNeovimDebian
    installSourcerer
    ;;
*)
    DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
    echo "Please define ${DIR##*/} installation for ${OS_TYPE}"
    exit 1
    ;;
esac
