#!/usr/bin/env bash

. "${HOME}"/.local/functions/dotfiles.sh

installNeovimMac() {
    dotfiles::bootstrap pyenv

    brew install neovim

    . "${HOME}"/.config/env/pyenv.env

    pyenv virtualenv python2 neovim2
    pyenv virtualenv python3 neovim3

    pyenv activate neovim2 &>/dev/null \
    pip install neovim
    pyenv deactivate

    pyenv activate neovim3 &>/dev/null
    pip install neovim flake8
    if [[ ! -f  ~/.local/bin/flake8 ]]; then
        ln -s `pyenv which flake8` ~/.local/bin/flake8  # Assumes that $HOME/bin is in $PATH
    fi
    pyenv deactivate
}

installNeovimDebian() {
    general::sudo apt-get install python-dev python-pip python3-dev python3-pip
    general::sudo add-apt-repository ppa:neovim-ppa/unstable
    general::sudo apt-get update
    general::sudo apt-get install neovim
}

installSourcerer() {
    if [[ ! -f ${XDG_CONFIG_HOME}/nvim/colors/sourcerer.vim ]]; then
        general::update_repo git://github.com/xero/sourcerer.git sourcerer
        popd
        ln -s ${CODE}/sourcerer/sourcerer.vim $XDG_CONFIG_HOME/nvim/colors/sourcerer.vim
    fi
}

installPlugins() {
    nvim -c :PlugInstall
}

installESLint() {
    if ! which eslint &>/dev/null; then
        general::sudo npm install -g eslint
    fi
}

installVimv() {
    if ! which vimv &>/dev/null; then
        general::update_repo git://github.com/thameera/vimv.git vimv
        popd
        ln -s "${CODE}/vimv/vimv" "${HOME}/.local/bin/vimv"
        chmod +x "{HOME}/.local/bin/vimv"
    fi
}

case "${OS_TYPE}" in
Darwin | Mac)
    installNeovimMac
    installSourcerer
    installPlugins
    brew tap neovim/neovim
    brew tap rogual/neovim-dot-app
    brew install neovim-dot-app
    ln -s /usr/local/opt/neovim-dot-app /Applications
    ;;
Arch)
    osinstall neovim python2-neovim python-neovim xsel
    installSourcerer
    installPlugins
    ;;
Debian)
    installNeovimDebian
    installSourcerer
    ;;
*)
    DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
    echo "Please define ${DIR##*/} installation for ${OS_TYPE}"
    exit 1
    ;;
esac
