#!/bin/sh

patches=" \
    https://dwm.suckless.org/patches/fakefullscreen/dwm-fakefullscreen-20170508-ceac8c9.diff \
"

. "$XDG_FUNCTIONS_HOME"/suckless.sh

suckless_build $(basename "${0}") && \
$(basename "${0}") ${@}
