#!/bin/sh

NODEJS_VERSION=12.7.0

asdf plugin-add nodejs
"${ASDF_DATA_DIR:-$HOME/.asdf}"/plugins/nodejs/bin/import-release-team-keyring && \
cd $HOME && \
    asdf install nodejs "${NODEJS_VERSION}" && \
    asdf global nodejs "${NODEJS_VERSION}"


if ! which yarn &>/dev/null; then
    npm install --global yarn
fi

# npm $@
