#!/bin/sh

# If ammending, skip template
IS_AMEND=$(ps -ocommand= -p $PPID | grep -e '--amend');

if [ -n "$IS_AMEND" ]; then
  exit 0;
fi

branch=$(git rev-parse --abbrev-ref HEAD)
grep -Ev "(# Please.*|# with.*|^#$)" $1 > /tmp/msg && cat /tmp/msg > $1

sed "1a\\$branch:" $1 > /tmp/msg && cat /tmp/msg > $1

if [ ! -z "$USES_JIRA" ]; then
	ticket_url="https://bonfyreapp.atlassian.net/browse/${branch#*/}"
	sed "6a\\$branch: $ticket_url" $1 > /tmp/msg && cat /tmp/msg > $1
fi
