#!/usr/bin/env bash

branch=$(git rev-parse --abbrev-ref HEAD)
grep -Ev "(# Please.*|# with.*|^#$)" $1 > /tmp/msg && cat /tmp/msg > $1
sed "1a\\
${branch}: " $1 > /tmp/msg && cat /tmp/msg > $1
sed "5a\\
${branch}" $1 > /tmp/msg && cat /tmp/msg > $1
