#!/usr/bin/env bash

. "${XDG_FUNCTIONS_DIR:-$HOME/.local/functions}"/dotfiles.sh

installMac() {
    osinstall https://raw.githubusercontent.com/choppsv1/homebrew-term24/master/tmux.rb reattach-to-user-namespace
}

installArch() {
    osinstall tmux
}

dotfiles::install tmux
